import torch
from torch.nn import Module
from utils.logits_processor import LogitsProcessor, GreedyProcessor
from transformers.cache_utils import DynamicCache
from utils.caching import prune_cache
import utils.printing as printing
from typing import List, Tuple
import time



def max_fn(x: torch.Tensor) -> torch.Tensor:
    """
    Max function.
        x: input tensor.
    Returns:
        tensor norm(max(0, x)).
    """
    x_max = torch.where(x > 0, x, torch.zeros_like(x))
    x_max_sum = torch.sum(x_max, dim=-1, keepdim=True)
    return x_max / x_max_sum


@torch.no_grad()
def speculative_generate(
    inputs: List[int],
    drafter: Module,
    target: Module,
    tokenizer = None,
    gamma: int = 5,
    logits_processor: LogitsProcessor = GreedyProcessor(),
    max_gen_len: int = 40,
    eos_tokens_id: int | List[int] = 1,
    pad_token_id: int = 0,
    use_cache: bool = False,
    skip_sample_adjustment: bool = False,
    first_target: bool = True,
    debug: bool = False,
    # beta: float=0.60
) -> Tuple[List[int], float]:
    """
    Generate text sequence using the speculative decoding algorithm.
    Implementation of Speculative Decoding. (https://arxiv.org/pdf/2211.17192.pdf)
    
    Args:
        inputs (List[int]): input sequence of batch size 1.
        drafter (Module): drafter model.
        target (Module): target model.
        tokenizer: tokenizer (used for debugging).
        gamma (int): number of drafts generated by the drafter at each step.
        logits_processor (LogitsProcessor): logits processor for sampling.
        max_gen_len (int): maximum length of the generated sequence.
        eos_tokens_id (int or List[int]): end token id (could be multiple).
        pad_token_id (int): pad token id.
        use_cache (bool): whether to use cache.
        skip_sample_adjustment (bool): whether to skip the sample adjustment step when some drafts are discarded.
        first_target (bool): whether to run the target model before the speculative algorithm.
        debug (bool): debug mode.
    
    Returns:
        List[int]: generated sequence.
        float: acceptance rate (number of accepted drafts divided by the number of total drafts).
        
    Note: This generation methods only works for decoder-only models.
    Note bis: The drafter and target models should output the same logits shape.
    Note ter: NgramModels are currently not supported.
    """
    
    drafter_cache, target_cache = None, None

    list_tokens_id = eos_tokens_id if isinstance(eos_tokens_id, list) else [eos_tokens_id]
    stop_tokens = torch.tensor(list_tokens_id, dtype=torch.long, device=target.device).unsqueeze(1)
    
    drafts_accepted, drafts_speculated = .0, .0
    
    vocabulary_size = target.config.vocab_size    
        
    # prepare input tensor
    prompt_len = len(inputs)
    max_seq_length = target.config.max_position_embeddings if hasattr(target.config, 'max_position_embeddings') else (target.config.max_context_length if hasattr(target.config, 'max_context_length') else 1024)
    total_len = min(max_seq_length, prompt_len + max_gen_len)
    input_ids = torch.full((1, total_len), pad_token_id, dtype=torch.long, device=target.device)
    input_ids[0, :prompt_len] = torch.tensor(inputs, dtype=torch.long, device=target.device)
    
    current_position = prompt_len
    
    if first_target:
        # run the target model before the speculative algorithm. Allows to prefill the kvcache and get a first token.
        Mp = target(
            input_ids=input_ids[..., :current_position],
            past_key_values=target_cache,
            use_cache=use_cache,
        )
        target_cache = Mp.past_key_values
        p_p = logits_processor(Mp.logits[..., -1, :])
        t = logits_processor.sample(p_p)
        input_ids[0, current_position] = t
        current_position += 1
        
        if torch.isin(t, stop_tokens):
            if debug:
                printing.end_token_found(0)
            return input_ids[0, prompt_len:current_position].tolist(), 0
        
        if debug:
            printing.initial_step(t, tokenizer)
    count_draft=0
    count_speculated=0
    epsilon = 1e-6
    preceding_alpha=0
    prev_gamma=gamma
    found=False
    extra_time=0
    count=0
    lt_gamma=[]
    preceding_alpha=0
    sum_gamma=0
    alpha=0
    coll_alpha=0
    alpha_list=[]
    n_collector=[] # no of tokeens accepted collecting it for calculating the expectation of the next predicted gamma
    expectation_sum=0
    expectation_sum_next=0
    count_till_ex=0
    decode_steps=[]
    decode_steps_new=[]
    expectation_collector=[]
    while current_position < total_len:
        count+=1
        count_till_ex+=1
        corrected_gamma = min(gamma, total_len - current_position - 1)
        print(corrected_gamma)
        sum_gamma+=corrected_gamma
        lt_gamma.append(corrected_gamma)
        q = torch.zeros((1, corrected_gamma, vocabulary_size), device=target.device)
        
        input_ids = input_ids.to(drafter.device)
        
        # generate gamma drafts
        for k in range(corrected_gamma):
            Mq = drafter(
                input_ids=input_ids[..., :current_position + k],
                past_key_values=drafter_cache,
                use_cache=use_cache,
            )
            drafter_cache = Mq.past_key_values
            
            draft_logits = Mq.logits[..., -1, :]
            draft_probs = logits_processor(draft_logits)
            q[0, k] = draft_probs.to(target.device)
            xi = logits_processor.sample(draft_probs)
            input_ids[0, current_position + k] = xi
        drafts_speculated += corrected_gamma
        input_ids = input_ids.to(target.device)
        
        # run target model on drafts and get logits of the previous tokens plus one more token
        Mp = target(
            input_ids=input_ids[..., :current_position + corrected_gamma],
            past_key_values=target_cache,
            use_cache=use_cache,
        )
        target_cache = Mp.past_key_values
        draft_logits = Mp.logits[..., current_position - 1:current_position + corrected_gamma - 1, :] # [1, corrected_gamma, vocab_size]
        p = logits_processor(draft_logits) # [1, gamma, vocab_size]
        
        # compute the last accepted draft position (rejection sampling)
        r = torch.rand(corrected_gamma, device=target.device)
        fractions = p / q
        n = corrected_gamma
        for i in range(corrected_gamma):
            if r[i] > fractions[0, i, input_ids[0, current_position + i]]:
                n = i
                break
        
        drafts_accepted += n
        print("drafts_accepted_iteratively= ", n, "drafts_accepted= ", drafts_accepted, "gamma= ", corrected_gamma)
        # # print("p= ", p,"q= ", q)
        # start=time.time()
        # p_copy = p.clone()
        # q_copy = q.clone()
        # # print("p_copy ", p_copy)
        # # print("q_copy ", q_copy)
        # min_pq = torch.minimum(p_copy, q_copy)  
        # alpha_t = min_pq.sum(dim=-1)
        # # print(sum_gamma)
        # alpha_t=alpha_t.mean().item()
        # coll_alpha+=(alpha_t.mean().item())*corrected_gamma
        # alpha = coll_alpha/sum_gamma
        # end=time.time()
        # expectation_sum+=(1-alpha_t**(corrected_gamma+1))/(1-alpha_t)
        # n_collector.append(alpha_t)
        # end=time.time()
        ## New here for calculating the theoretical no.of steps for decoding
        # alpha_itr = n/corrected_gamma
        # if(alpha_itr==1):
        #     expectation_sum+=corrected_gamma+1
        #     # expectation_sum_next+=
        # else:
        #     expectation_sum+=(1-alpha_itr**(corrected_gamma+1))/(1-alpha_itr)

        count_till_ex += 1
        # expectation_collector.append(expectation_sum)
        # done here

        if((drafts_accepted - count_draft)>=1):
        #     # print(f"Average alpha (E[min(p,q)]) across all positions = {alpha:.6f}")
        #     # alpha=0
        #     # sum_gamma=0
            # alpha=drafts_accepted/drafts_speculated
            lt_gamma.append([corrected_gamma,count_till_ex])
            # expectation_mean = expectation_sum/count_till_ex
            if(preceding_alpha==0):
                preceding_alpha=alpha
            # alpha=0.9*alpha+0.1*preceding_alpha
            alpha=0.9*(drafts_accepted-count_draft)/(drafts_speculated-count_speculated) + 0.1*preceding_alpha
            # alpha=0.9*(drafts_accepted)/(drafts_speculated) + 0.1*preceding_alpha

            alpha_list.append(alpha)
            preceding_alpha=alpha

            sp=[]
            # print(alpha)
            i=2
            
            while (i<20):
                if(alpha==1):
                    break
                sp_ele=(1-alpha**(i+1))/((1-alpha)*(i*(0.08799)+1))
                sp.append(sp_ele)
                i+=1
            print(sp)
            start_ji=time.time()
            # print("prev_gamma: ", prev_gamma)
            if(alpha==1):
                gamma=gamma
                found=True
            
            else:  
            
                for j in range(len(sp)):
                    if(max(sp)>1):
                        if(sp[prev_gamma-2]<1):
                            gamma=gamma-1
                            found=True
                            break
                            
                        elif(sp[j]>1 and (sp.index(sp[j])+2-prev_gamma)==1):
                            gamma= sp.index(sp[j])+2
                            found=True
                            break
                        # elif(sp[j]>1 and (sp.index(sp[j])+2-prev_gamma)==2):
                        #     gamma= sp.index(sp[j])+2
                        #     found=True
                        
                    
                    elif(abs(sp.index(max(sp))+2-prev_gamma)>1):
                        gamma+=1
                
                        if((prev_gamma-sp.index(max(sp))-2)>1):
                            gamma-=2
                        found=True
                        break
            # New here for calculating the theoretical no.of steps for decoding
            # print("length of n_collector: ", len(n_collector))
            # print(n_collector)
            # print(gamma)
            # for i in range(len(n_collector)):
            #     # alpha_itr = n_collector[i]/corrected_gamman_collector[i]
            #     expectation_sum_next += (1-n_collector[i]**(5))/(1-n_collector[i])
            #     # if(alpha_itr==1):
            #     #     expectation_sum_next += gamma+1
            #     # else:
            #     #     expectation_sum_next += (1-alpha_itr**(gamma+1))/(1-alpha_itr)
            # expectation_mean_next = expectation_sum_next/count_till_ex
            # decode_steps.append((drafts_accepted - count_draft)/expectation_mean)
            # decode_steps_new.append((drafts_accepted - count_draft)/expectation_mean_next)
            # print("Theoretical decode steps with Yi: ", (drafts_accepted - count_draft)/expectation_mean)
            # print("Theoretical decode steps with Yi+1: ", (drafts_accepted - count_draft)/expectation_mean_next)
            # done here
            end_ji=time.time()
            extra_time+=(end_ji-start_ji)#+end-start
            # if(found==False):
            #     gamma=sp.index(max(sp))+2
            # gamma=sp.index(max(sp))+2
            # if(gamma==2):
            #     gamma=4
            # print("aaya to hu bro")
            count_draft=drafts_accepted
            preceding_alpha=alpha
            count_speculated=drafts_speculated
            prev_gamma=gamma
            coll_alpha=0
            sum_gamma=0
            expectation_sum_next=0
            expectation_sum=0
            n_collector=[]
            count_till_ex=0

        # yha se commentout kro/ yha se comment in kro
            # expectation=(1-alpha**(corrected_gamma+1))/(1-alpha)
        #     print(f"Average alpha (E[min(p,q)]) across all positions = {alpha:.6f}")
        #     # print("Expectation: ", expectation)
            




        # check if the end token is in the drafts
        stop_locations = torch.nonzero(torch.eq(input_ids[..., current_position:current_position + n], stop_tokens))
        if stop_locations.shape[0] > 0:
            stop_location = stop_locations[0, 1].item()
            if debug:
                printing.end_token_found(stop_location)
            # print("count: ", count)
            return input_ids[0, prompt_len:current_position + stop_location + 1].tolist(), drafts_accepted / drafts_speculated, extra_time, count, lt_gamma #, alpha_list, decode_steps, decode_steps_new

        # adjust the distribution from Mp
        if n == corrected_gamma:
            p_p = Mp.logits[..., current_position + corrected_gamma - 1, :]
            p_p = logits_processor(p_p)
        else:
            # prune the cache
            if use_cache:
                drafter_cache = prune_cache(drafter_cache, corrected_gamma - n)
                target_cache = prune_cache(target_cache, corrected_gamma - n + 1)
            
            if not skip_sample_adjustment:
                p_p = max_fn(p[..., n, :] - q[0, n, :])
            else:
                p_p = p[..., n, :]
        x = logits_processor.sample(p_p)
        
        if debug:
            generated = input_ids.clone().detach()
            
        input_ids[0, current_position + n:current_position + corrected_gamma] = pad_token_id
        input_ids[0, current_position + n] = x
        
        if debug:
            printing.speculative_step(tokenizer, generated, input_ids, n, prompt_len, current_position, corrected_gamma)
            
        current_position += n + 1
        
        if torch.isin(x, stop_tokens):
            if debug:
                printing.end_token_found(n)
            # print("count: ", count)
            return input_ids[0, prompt_len:current_position].tolist(), drafts_accepted / drafts_speculated, extra_time, count, lt_gamma#, alpha_list, decode_steps, decode_steps_new
    # print("count: ", count)
    return input_ids[0, prompt_len:].tolist(), drafts_accepted / drafts_speculated, extra_time, count, lt_gamma#, alpha_list, decode_steps, decode_steps_new

